name: 'GitHub Actions Weather Bot'

on:
  push:
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: 'Get Weather'
        run: bash ./weather.sh

      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=UTC-8 date '+%Y-%m-%d %T')" >> $GITHUB_ENV

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_NAME }}
          password: ${{ secrets.MAIL_PASS }}
          subject: Shenzhen Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: enderhoshi@gmail.com
          from: GitHub Actions
          content_type: text/html

      # 向钉钉发送消息
      #- name: dingtalk
      #  uses: JantHsueh/webrequest-action@master
      #  with:
      #    url: ${{ secrets.DINGTALK_WEBHOOK }}
      #    method: POST
      #    payload: '{"msgtype": "text", "text": {"content": "西雾代理商-测试版(debug)-App更新-版本号: ${{ steps.apk.outputs.versionNum }},可直接在App中更新到最新版 \n 距上个正式版的更新记录: \n${{ steps.git_log.outputs.log }}"}}'
      #    headers: '{"Content-Type": "application/json"}'
